config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get '/orders/:id', to: 'orders#show', as: 'patient'
  post 'orders/import'

  root 'orders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :order
  belongs_to :patient
end

app/models/order.rb
class Order < ApplicationRecord
  self.primary_key = 'order_id'
  has_many :invoices, -> { where state: 'active' }
  has_many :patients, -> { where(state: 'active') }, through: :invoices

  scope :active, -> { where(state: 'active') }

  def self.process(uploaded_io)
    begin
      filename = Rails.root.join('public', uploaded_io.original_filename)
      File.open(filename, 'w') do |file|
        file.write(uploaded_io.read)
      end
      import(filename)
    rescue => exception
      puts exception
      return false
    end
  end

  def self.import(filename)
    data = SmarterCSV.process(filename)
    success = true

    if data.first.keys.include?(:patient_name)

      data.each do |entry|
        current = Patient.find_or_create_by(patient_id: entry[:patient_id])
        current.patient_name = entry[:patient_name]
        current.state = entry[:state]
        current.save(validate: false)
      end

    elsif data.first.keys.include?(:category)

      data.each do |entry|
        current = Order.find_or_create_by(order_id: entry[:order_id])
        current.category = entry[:category]
        current.state = entry[:state]
        current.save(validate: false)
      end

    elsif data.first.keys.include?(:patient_id) && data.first.keys.include?(:order_id)

      data.each do |entry|
        current = Invoice.where({patient_id: entry[:patient_id], order_id: entry[:order_id]}).first
        if current
          current.state = entry[:state]
        else
          current = Invoice.new(entry)
        end
        current.save(validate: false)
      end
    else
      success = false
    end
    success
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  self.primary_key = "patient_id"
  has_many :invoices
  has_many :orders, through: :invoices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.active

  end

  def import
    if Order.process(params[:file])
      message = 'Data imported'
    else
      message = 'The data was not imported'
    end
    redirect_to root_url, notice: message
  end

  def show
    order = Order.find(params[:id])
    @patients = order.patients
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CvsUploader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Import a file</h1>

<%= form_tag orders_import_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.category, patient_path(order) %></td>
        <td><%= order.state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients with active Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Patient name</th>
      <th>Patient state</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.patient_name %></td>
        <td><%= patient.state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Active Orders', root_path %>